musify:
  outputs:
    dev:
      dataset: musify_stg
      fixed_retries: 1
      keyfile: /.google/credentials/google_credentials.json
      location: us-central1
      method: service-account
      priority: interactive
      project: musify-354416
      threads: 4
      timeout_seconds: 300
      type: bigquery
    prod:
      dataset: musify_prod
      fixed_retries: 1
      keyfile: /.google/credentials/google_credentials.json
      location: us-central1
      method: service-account
      priority: interactive
      project: musify-354416
      threads: 4
      timeout_seconds: 300
      type: bigquery
  target: dev